import BUILTIN_SCREEN from "./BUILTIN_SCREEN.tsx";
import TEST_WIDGET from "./TEST_WIDGET.tsx";
import BUILTIN_LIST from "./BUILTIN_LIST.tsx";
import BUILTIN_OBJECT from "./BUILTIN_OBJECT.tsx";
import BUILTIN_CONTROL from "./BUILTIN_CONTROL.tsx";
import BUILTIN_FUNCTION from "./BUILTIN_FUNCTION.tsx";
import BUILTIN_OPERATION from "./BUILTIN_OPERATION.tsx";
import BUILTIN_VARIABLE from "./BUILTIN_VARIABLE.tsx";
import BUILTIN_EVENT from "./BUILTIN_EVENT.tsx";
import BUILTIN_FEATURE from "./BUILTIN_FEATURE.tsx";

const BUILTIN_WIDGETS = [
    BUILTIN_EVENT,
    BUILTIN_CONTROL,
    BUILTIN_OPERATION,
    BUILTIN_FEATURE,
    BUILTIN_FUNCTION,
    BUILTIN_VARIABLE,
    BUILTIN_OBJECT,
    BUILTIN_LIST,
    BUILTIN_SCREEN,
    TEST_WIDGET,
]
export default BUILTIN_WIDGETS;